exports.parts = [
  {
    partNumber: "BS19514LEO677",
    brand: "BRIDGESTONE",
    name: "LEO677",
    costPrice: 2500,
    sellingPrice: 2850,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "195",
      aspectRatio: null,
      rimDiameter: "14",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "BS19514DRVR624",
    brand: "BRIDGESTONE",
    name: "DURAVIS R624",
    costPrice: 2250,
    sellingPrice: 2650,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "195",
      aspectRatio: null,
      rimDiameter: "14",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "BS2157015DRVR611",
    brand: "BRIDGESTONE",
    name: "DURAVIS R611",
    costPrice: 2660,
    sellingPrice: 3000,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "215",
      aspectRatio: "70",
      rimDiameter: "15",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "BS2156516DRVR611",
    brand: "BRIDGESTONE",
    name: "DURAVIS R611",
    costPrice: 3090,
    sellingPrice: 3450,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "215",
      aspectRatio: "65",
      rimDiameter: "16",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "BS2157016DRVR611",
    brand: "BRIDGESTONE",
    name: "DURAVIS R611",
    costPrice: 0,
    sellingPrice: 3650,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "215",
      aspectRatio: "70",
      rimDiameter: "16",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "BS2457016HT689",
    brand: "BRIDGESTONE",
    name: "H/T 689",
    costPrice: 4350,
    sellingPrice: 4800,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "245",
      aspectRatio: "70",
      rimDiameter: "16",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "BS2656517HT684",
    brand: "BRIDGESTONE",
    name: "H/T 684",
    costPrice: 4250,
    sellingPrice: 4800,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "265",
      aspectRatio: "65",
      rimDiameter: "17",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "BS2656018HT684II",
    brand: "BRIDGESTONE",
    name: "H/T 684 II",
    costPrice: 5330,
    sellingPrice: 5950,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "265",
      aspectRatio: "60",
      rimDiameter: "18",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "MC2257514XCD2",
    brand: "MICHELIN",
    name: "XCD2",
    costPrice: 4230,
    sellingPrice: 4650,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "225",
      aspectRatio: "75",
      rimDiameter: "14",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "MC2157015AGL",
    brand: "MICHELIN",
    name: "AGILIS",
    costPrice: 2700,
    sellingPrice: 3100,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "215",
      aspectRatio: "70",
      rimDiameter: "15",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "MC2257515XCD2",
    brand: "MICHELIN",
    name: "XCD2",
    costPrice: 4650,
    sellingPrice: 5000,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "225",
      aspectRatio: "75",
      rimDiameter: "15",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "LL1757013CWET",
    brand: "LINGLONG",
    name: "CROSSWIND ET",
    costPrice: 990,
    sellingPrice: 1350,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "175",
      aspectRatio: "70",
      rimDiameter: "13",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "LL1856514CWHP010",
    brand: "LINGLONG",
    name: "CROSSWIND HP010",
    costPrice: 1090,
    sellingPrice: 1450,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "185",
      aspectRatio: "65",
      rimDiameter: "14",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "LL19514GMVP",
    brand: "LINGLONG",
    name: "GREEN-MAX VAN PLUS",
    costPrice: 1390,
    sellingPrice: 1750,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "195",
      aspectRatio: null,
      rimDiameter: "14",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "LL19514R666",
    brand: "LINGLONG",
    name: "RADIAL 666",
    costPrice: 1390,
    sellingPrice: 1750,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "195",
      aspectRatio: null,
      rimDiameter: "14",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "LL1855515CM",
    brand: "LINGLONG",
    name: "COMFORT MASTER",
    costPrice: 0,
    sellingPrice: 1550,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "185",
      aspectRatio: "55",
      rimDiameter: "15",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "LL1856015CWHP010",
    brand: "LINGLONG",
    name: "CROSSWIND HP010",
    costPrice: 1140,
    sellingPrice: 1550,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "185",
      aspectRatio: "60",
      rimDiameter: "15",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "LL1955015CW",
    brand: "LINGLONG",
    name: "CROSSWIND",
    costPrice: 1100,
    sellingPrice: 1500,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "195",
      aspectRatio: "50",
      rimDiameter: "15",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "LL1956015CWHP010",
    brand: "LINGLONG",
    name: "CROSSWIND HP010",
    costPrice: 1160,
    sellingPrice: 1550,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "195",
      aspectRatio: "60",
      rimDiameter: "15",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "LL2057015GMVP",
    brand: "LINGLONG",
    name: "GREEN-MAX VAN PLUS",
    costPrice: 1510,
    sellingPrice: 1900,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "205",
      aspectRatio: "70",
      rimDiameter: "15",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "LL2157015GMVP",
    brand: "LINGLONG",
    name: "GREEN-MAX VAN PLUS",
    costPrice: 1590,
    sellingPrice: 1950,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "215",
      aspectRatio: "70",
      rimDiameter: "15",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "LL2557015CWAT",
    brand: "LINGLONG",
    name: "CROSSWIND A/T",
    costPrice: 2340,
    sellingPrice: 2800,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "255",
      aspectRatio: "70",
      rimDiameter: "15",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "LL1855516CWHP010",
    brand: "LINGLONG",
    name: "CROSSWIND HP010",
    costPrice: 1170,
    sellingPrice: 1600,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "185",
      aspectRatio: "55",
      rimDiameter: "16",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "LL2055516CWHP010",
    brand: "LINGLONG",
    name: "CROSSWIND HP010",
    costPrice: 1410,
    sellingPrice: 1800,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "205",
      aspectRatio: "55",
      rimDiameter: "16",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "LL2156516CW",
    brand: "LINGLONG",
    name: "CROSSWIND",
    costPrice: 1950,
    sellingPrice: 2300,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "215",
      aspectRatio: "65",
      rimDiameter: "16",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "LL2156516CW4X4HP",
    brand: "LINGLONG",
    name: "CROSSWIND 4X4 HP",
    costPrice: 1680,
    sellingPrice: 2100,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "215",
      aspectRatio: "65",
      rimDiameter: "16",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "LL2157016CW4X4HP",
    brand: "LINGLONG",
    name: "CROSSWIND 4X4 HP",
    costPrice: 1820,
    sellingPrice: 2300,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "215",
      aspectRatio: "70",
      rimDiameter: "16",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "LL2457016CW4X4HP",
    brand: "LINGLONG",
    name: "CROSSWIND 4X4 HP",
    costPrice: 2060,
    sellingPrice: 2550,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "245",
      aspectRatio: "70",
      rimDiameter: "16",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "LL2657016CW4X4HP",
    brand: "LINGLONG",
    name: "CROSSWIND 4X4 HP",
    costPrice: 2250,
    sellingPrice: 2700,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "265",
      aspectRatio: "70",
      rimDiameter: "16",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "LL2656517CW4X4HP",
    brand: "LINGLONG",
    name: "CROSSWIND 4X4 HP",
    costPrice: 2480,
    sellingPrice: 3100,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "265",
      aspectRatio: "65",
      rimDiameter: "17",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "LL2656517CWAT2",
    brand: "LINGLONG",
    name: "CROSSWIND AT-2",
    costPrice: 2870,
    sellingPrice: 3100,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "265",
      aspectRatio: "65",
      rimDiameter: "17",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "LL2656018CW4X4HP",
    brand: "LINGLONG",
    name: "CROSSWIND 4X4 HP",
    costPrice: 2540,
    sellingPrice: 3300,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "265",
      aspectRatio: "60",
      rimDiameter: "18",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "LL2656018CWAT2",
    brand: "LINGLONG",
    name: "CROSSWIND AT-2",
    costPrice: 2970,
    sellingPrice: 3600,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "265",
      aspectRatio: "60",
      rimDiameter: "18",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "LL2656018CW",
    brand: "LINGLONG",
    name: "CROSSWIND",
    costPrice: 2680,
    sellingPrice: 3500,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "265",
      aspectRatio: "60",
      rimDiameter: "18",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "MX1757013MAP5",
    brand: "MAXXIS",
    name: "MA-P5",
    costPrice: 1070,
    sellingPrice: 1400,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "175",
      aspectRatio: "70",
      rimDiameter: "13",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "MX1856514MAP5",
    brand: "MAXXIS",
    name: "MA-P5",
    costPrice: 1160,
    sellingPrice: 1500,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "185",
      aspectRatio: "65",
      rimDiameter: "14",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "MX19514MA579",
    brand: "MAXXIS",
    name: "MA-579",
    costPrice: 1670,
    sellingPrice: 2000,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "195",
      aspectRatio: null,
      rimDiameter: "14",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "MX20514MCV5",
    brand: "MAXXIS",
    name: "MCV-5",
    costPrice: 2330,
    sellingPrice: 2650,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "205",
      aspectRatio: null,
      rimDiameter: "14",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "MX2257514MCV5",
    brand: "MAXXIS",
    name: "MCV-5",
    costPrice: 2620,
    sellingPrice: 3100,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "225",
      aspectRatio: "75",
      rimDiameter: "14",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "MX1855515MAP5",
    brand: "MAXXIS",
    name: "MA-P5",
    costPrice: 1400,
    sellingPrice: 1750,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "185",
      aspectRatio: "55",
      rimDiameter: "15",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "MX1856015MAP3",
    brand: "MAXXIS",
    name: "MA-P3",
    costPrice: 1350,
    sellingPrice: 1550,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "185",
      aspectRatio: "60",
      rimDiameter: "15",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "MX1856015MAP5",
    brand: "MAXXIS",
    name: "MA-P5",
    costPrice: 0,
    sellingPrice: 1700,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "185",
      aspectRatio: "60",
      rimDiameter: "15",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "MX1955515MAP5",
    brand: "MAXXIS",
    name: "MA-P5",
    costPrice: 1380,
    sellingPrice: 1750,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "195",
      aspectRatio: "55",
      rimDiameter: "15",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "MX1956015MAP5",
    brand: "MAXXIS",
    name: "MA-P5",
    costPrice: 1210,
    sellingPrice: 1550,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "195",
      aspectRatio: "60",
      rimDiameter: "15",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "MX1956515MAP5",
    brand: "MAXXIS",
    name: "MA-P5",
    costPrice: 1250,
    sellingPrice: 1600,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "195",
      aspectRatio: "65",
      rimDiameter: "15",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "MX2057015MA579",
    brand: "MAXXIS",
    name: "MA-579",
    costPrice: 0,
    sellingPrice: 2150,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "205",
      aspectRatio: "70",
      rimDiameter: "15",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "MX2157015MA579",
    brand: "MAXXIS",
    name: "MA-579",
    costPrice: 1950,
    sellingPrice: 2250,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "215",
      aspectRatio: "70",
      rimDiameter: "15",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "MX2157015MCV5",
    brand: "MAXXIS",
    name: "MCV-5",
    costPrice: 2380,
    sellingPrice: 2850,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "215",
      aspectRatio: "70",
      rimDiameter: "15",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "MX2257515MCV5",
    brand: "MAXXIS",
    name: "MCV-5",
    costPrice: 2730,
    sellingPrice: 3200,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "225",
      aspectRatio: "75",
      rimDiameter: "15",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "MX1855516MAP5",
    brand: "MAXXIS",
    name: "MA-P5",
    costPrice: 1630,
    sellingPrice: 1950,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "185",
      aspectRatio: "55",
      rimDiameter: "16",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "MX1955516PROR1",
    brand: "MAXXIS",
    name: "PRO R1",
    costPrice: 2300,
    sellingPrice: 1860,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "195",
      aspectRatio: "55",
      rimDiameter: "16",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "MX2055516MAP5",
    brand: "MAXXIS",
    name: "MA-P5",
    costPrice: 1590,
    sellingPrice: 2000,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "205",
      aspectRatio: "55",
      rimDiameter: "16",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "MX2156516MA579",
    brand: "MAXXIS",
    name: "MA-579",
    costPrice: 2320,
    sellingPrice: 2700,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "215",
      aspectRatio: "65",
      rimDiameter: "16",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "MX2157016HPM3",
    brand: "MAXXIS",
    name: "HP-M3",
    costPrice: 2310,
    sellingPrice: 2700,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "215",
      aspectRatio: "70",
      rimDiameter: "16",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "MX2457016AT700",
    brand: "MAXXIS",
    name: "AT-700",
    costPrice: 2690,
    sellingPrice: 3150,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "245",
      aspectRatio: "70",
      rimDiameter: "16",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "MX2657016AT700",
    brand: "MAXXIS",
    name: "AT-700",
    costPrice: 2840,
    sellingPrice: 3250,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "265",
      aspectRatio: "70",
      rimDiameter: "16",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "MX2054517HP5",
    brand: "MAXXIS",
    name: "HP-5",
    costPrice: 1740,
    sellingPrice: 2150,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "205",
      aspectRatio: "45",
      rimDiameter: "17",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "MX2155517IPRO",
    brand: "MAXXIS",
    name: "I-PRO",
    costPrice: 1950,
    sellingPrice: 2400,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "215",
      aspectRatio: "55",
      rimDiameter: "17",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "MX2656517HPM3",
    brand: "MAXXIS",
    name: "HP-M3",
    costPrice: 3350,
    sellingPrice: 3800,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "265",
      aspectRatio: "65",
      rimDiameter: "17",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "MX2656018HPM3",
    brand: "MAXXIS",
    name: "HP-M3",
    costPrice: 3570,
    sellingPrice: 3900,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "265",
      aspectRatio: "65",
      rimDiameter: "17",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "MX2656018AT700",
    brand: "MAXXIS",
    name: "AT-700",
    costPrice: 3020,
    sellingPrice: 3800,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "265",
      aspectRatio: "60",
      rimDiameter: "18",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "MX2655020AT700",
    brand: "MAXXIS",
    name: "AT-700",
    costPrice: 3720,
    sellingPrice: 0,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "265",
      aspectRatio: "50",
      rimDiameter: "20",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "MX2655020AT700",
    brand: "MAXXIS",
    name: "HP-M3",
    costPrice: 3760,
    sellingPrice: 0,
    unit: "เส้น",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: {
      width: "265",
      aspectRatio: "50",
      rimDiameter: "20",
    },
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 3,
  },
  {
    partNumber: "SB-3972",
    brand: "555",
    name: "ลูกหมากปีกนกล่าง Commuter",
    costPrice: 0,
    sellingPrice: 950,
    unit: "ตัว",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: undefined,
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 2,
  },
  {
    partNumber: "SB-1722",
    brand: "555",
    name: "ลูกหมากปีกนกล่าง BT50",
    costPrice: 0,
    sellingPrice: 1050,
    unit: "ตัว",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: undefined,
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 2,
  },
  {
    partNumber: "SB-2482",
    brand: "555",
    name: "ลูกหมากปีกนกล่าง Hiace LH112,125",
    costPrice: 0,
    sellingPrice: 850,
    unit: "ตัว",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: undefined,
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 2,
  },
  {
    partNumber: "SB-1522",
    brand: "555",
    name: "ลูกหมากปีกนกล่าง Mazda Fighter/Ford Ranger 2WD",
    costPrice: 0,
    sellingPrice: 790,
    unit: "ตัว",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: undefined,
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 2,
  },
  {
    partNumber: "SB-1542",
    brand: "555",
    name: "ลูกหมากปีกนกล่าง Mazda Fighter/Ford Ranger 4WD",
    costPrice: 0,
    sellingPrice: 890,
    unit: "ตัว",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: undefined,
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 2,
  },
  {
    partNumber: "SB-N252",
    brand: "555",
    name: "ลูกหมากปีกนกล่าง Navara07-13",
    costPrice: 0,
    sellingPrice: 790,
    unit: "ตัว",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: undefined,
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 2,
  },
  {
    partNumber: "SB-7152",
    brand: "555",
    name: "ลูกหมากปีกนกล่าง L-200/Strada",
    costPrice: 0,
    sellingPrice: 690,
    unit: "ตัว",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: undefined,
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 2,
  },
  {
    partNumber: "SB-7842",
    brand: "555",
    name: "ลูกหมากปีกนกล่าง Triton/Pajero 2WD/4WD",
    costPrice: 0,
    sellingPrice: 950,
    unit: "ตัว",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: undefined,
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 2,
  },
  {
    partNumber: "SB-5302",
    brand: "555",
    name: "ลูกหมากปีกนกล่าง D-Max 2-4WD/TFR 4WD",
    costPrice: 0,
    sellingPrice: 850,
    unit: "ตัว",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: undefined,
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 2,
  },
  {
    partNumber: "SB-4672",
    brand: "555",
    name: "ลูกหมากปีกนกล่าง Big M/Frontier",
    costPrice: 0,
    sellingPrice: 790,
    unit: "ตัว",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: undefined,
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 2,
  },
  {
    partNumber: "SB-2832",
    brand: "555",
    name: "ลูกหมากปีกนกล่าง Mighty-X/Tiger",
    costPrice: 0,
    sellingPrice: 850,
    unit: "ตัว",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: undefined,
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 2,
  },
  {
    partNumber: "SB-5282",
    brand: "555",
    name: "ลูกหมากปีกนกล่าง TFR",
    costPrice: 0,
    sellingPrice: 850,
    unit: "ตัว",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: undefined,
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 2,
  },
  {
    partNumber: "SB-5144",
    brand: "555",
    name: "ลูกหมากปีกนกล่าง KBZ",
    costPrice: 0,
    sellingPrice: 760,
    unit: "ตัว",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: undefined,
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 2,
  },
  {
    partNumber: "UC2R-34550แท้ศูนย์",
    brand: "แท้ศูนย์",
    name: "ลูกหมากปีกนกล่าง Ford Ranger,Everest/BT50-Pro",
    costPrice: 0,
    sellingPrice: 1550,
    unit: "ตัว",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: undefined,
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 2,
  },
  {
    partNumber: "SE-5381",
    brand: "555",
    name: "ลูกหมากคันชัก-นอก D-max All New/V-cross/Mu-X",
    costPrice: 0,
    sellingPrice: 570,
    unit: "ตัว",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: undefined,
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 2,
  },
  {
    partNumber: "SE-3881",
    brand: "555",
    name: "ลูกหมากคันชัก-นอก Vigo/Revo 2WD",
    costPrice: 0,
    sellingPrice: 520,
    unit: "ตัว",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: undefined,
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 2,
  },
  {
    partNumber: "SE-3891",
    brand: "555",
    name: "ลูกหมากคันชัก-นอก Vigo 4WD/Fortuner",
    costPrice: 0,
    sellingPrice: 530,
    unit: "ตัว",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: undefined,
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 2,
  },
  {
    partNumber: "SE-5361",
    brand: "555",
    name: "ลูกหมากคันชัก-นอก D-max 2-4WD",
    costPrice: 0,
    sellingPrice: 530,
    unit: "ตัว",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: undefined,
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 2,
  },
  {
    partNumber: "SE-7941",
    brand: "111",
    name: "ลูกหมากคันชัก-นอก Triton'05 2WD",
    costPrice: 0,
    sellingPrice: 360,
    unit: "ตัว",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: undefined,
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 2,
  },
  {
    partNumber: "SE-1521",
    brand: "111",
    name: "ลูกหมากคันชัก-นอก Magnum/Thunder",
    costPrice: 0,
    sellingPrice: 320,
    unit: "ตัว",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: undefined,
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 2,
  },
  {
    partNumber: "SE-2471",
    brand: "111",
    name: "ลูกหมากคันชัก-นอก MTX/Tiger",
    costPrice: 0,
    sellingPrice: 295,
    unit: "ตัว",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: undefined,
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 2,
  },
  {
    partNumber: "SE-4671",
    brand: "111",
    name: "ลูกหมากคันชัก-นอก Big-M",
    costPrice: 0,
    sellingPrice: 295,
    unit: "ตัว",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: undefined,
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 2,
  },
  {
    partNumber: "SE-N191",
    brand: "111",
    name: "ลูกหมากคันชัก-นอก Frontier zd3.0",
    costPrice: 0,
    sellingPrice: 320,
    unit: "ตัว",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: undefined,
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 2,
  },
  {
    partNumber: "SE-7731",
    brand: "111",
    name: "ลูกหมากคันชัก-นอก Strada 2WD",
    costPrice: 0,
    sellingPrice: 350,
    unit: "ตัว",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: undefined,
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 2,
  },
  {
    partNumber: "SE-4821",
    brand: "111",
    name: "ลูกหมากคันชัก-นอก Frontier TD27",
    costPrice: 0,
    sellingPrice: 350,
    unit: "ตัว",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: undefined,
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 2,
  },
  {
    partNumber: "SE-1541",
    brand: "555",
    name: "ลูกหมากคันชัก-นอก Ford",
    costPrice: 0,
    sellingPrice: 550,
    unit: "ตัว",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: undefined,
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 2,
  },
  {
    partNumber: "SE-7071",
    brand: "BK",
    name: "ลูกหมากคันชัก-นอก L-200 Cyclone",
    costPrice: 0,
    sellingPrice: 290,
    unit: "ตัว",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: undefined,
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 2,
  },
  {
    partNumber: "MR508136R-5L",
    brand: "Pro(OEM)",
    name: "ลูกหมากคันชัก-นอก R-L Triton'05 4WD",
    costPrice: 0,
    sellingPrice: 880,
    unit: "คู่",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: undefined,
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 2,
  },
  {
    partNumber: "YB02-4020",
    brand: "Yamoto",
    name: "ยางหุ้มเพลาขับ-นอก Civic",
    costPrice: 0,
    sellingPrice: 350,
    unit: "ตัว",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: undefined,
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 2,
  },
  {
    partNumber: "SI-4920",
    brand: "111",
    name: "กล้องยาพวงมาลัย Frontier ZDI3.0",
    costPrice: 0,
    sellingPrice: 850,
    unit: "ตัว",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: undefined,
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 2,
  },
  {
    partNumber: "SI-1530",
    brand: "111",
    name: "กล้องยาพวงมาลัย Mazda Magnum/Thunder",
    costPrice: 0,
    sellingPrice: 900,
    unit: "ตัว",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: undefined,
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 2,
  },
  {
    partNumber: "SI-9440",
    brand: "111",
    name: "กล้องยาพวงมาลัย Ford Ranger TDCi/Mazda BT-50",
    costPrice: 0,
    sellingPrice: 950,
    unit: "ตัว",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: undefined,
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 2,
  },
  {
    partNumber: "SI-1620",
    brand: "111",
    name: "กล้องยาพวงมาลัย Ford Ranger/Mazda Fighter 2-4WD",
    costPrice: 0,
    sellingPrice: 950,
    unit: "ตัว",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: undefined,
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 2,
  },
  {
    partNumber: "SI-7152",
    brand: "111",
    name: "กล้องยาพวงมาลัย Mitsubishi L-200,Cyclone",
    costPrice: 0,
    sellingPrice: 990,
    unit: "ตัว",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: undefined,
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 2,
  },
  {
    partNumber: "SI-5140",
    brand: "111",
    name: "กล้องยาพวงมาลัย TFR 2WD/KBZ",
    costPrice: 0,
    sellingPrice: 750,
    unit: "ตัว",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: undefined,
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 2,
  },
  {
    partNumber: "SI-4670",
    brand: "111",
    name: "กล้องยาพวงมาลัย Big-M",
    costPrice: 0,
    sellingPrice: 790,
    unit: "ตัว",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: undefined,
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 2,
  },
  {
    partNumber: "SI-3620",
    brand: "111",
    name: "กล้องยาพวงมาลัย Tiger 2WD",
    costPrice: 0,
    sellingPrice: 850,
    unit: "ตัว",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: undefined,
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 2,
  },
  {
    partNumber: "SI-4820",
    brand: "111",
    name: "กล้องยาพวงมาลัย Frontier TD27",
    costPrice: 0,
    sellingPrice: 850,
    unit: "ตัว",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: undefined,
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 2,
  },
  {
    partNumber: "SI-2830",
    brand: "111",
    name: "กล้องยาพวงมาลัย MTX 2WD",
    costPrice: 0,
    sellingPrice: 790,
    unit: "ตัว",
    stockQuantity: 4,
    minStockLevel: 2,
    typeSpecificData: undefined,
    compatibleVehicles: undefined,
    publicId: null,
    secureUrl: null,
    categoryId: 2,
  },
];
