// ข้อมูลยี่ห้อรถยนต์
export const carBrands = [
  { id: "Toyota", name: "Toyota" },
  { id: "Honda", name: "Honda" },
  { id: "Isuzu", name: "Isuzu" },
  { id: "Nissan", name: "Nissan" },
  { id: "Mazda", name: "Mazda" },
  { id: "Mitsubishi", name: "Mitsubishi" },
  { id: "Ford", name: "Ford" },
  { id: "Chevrolet", name: "Chevrolet" },
  { id: "Suzuki", name: "Suzuki" },
  { id: "Subaru", name: "Subaru" },
  { id: "BMW", name: "BMW" },
  { id: "Mercedes-Benz", name: "Mercedes-Benz" },
  { id: "Audi", name: "Audi" },
  { id: "Volkswagen", name: "Volkswagen" },
  { id: "Hyundai", name: "Hyundai" },
  { id: "Kia", name: "Kia" },
  { id: "Volvo", name: "Volvo" },
  { id: "Lexus", name: "Lexus" },
  { id: "Acura", name: "Acura" },
  { id: "Infiniti", name: "Infiniti" },
];

// ข้อมูลรุ่นรถตามยี่ห้อ
export const carModels = {
  Toyota: [
    { id: "Hilux Revo", name: "Hilux Revo" },
    { id: "Fortuner", name: "Fortuner" },
    { id: "Vios", name: "Vios" },
    { id: "Yaris", name: "Yaris" },
    { id: "Camry", name: "Camry" },
    { id: "Corolla", name: "Corolla" },
    { id: "C-HR", name: "C-HR" },
    { id: "Innova", name: "Innova" },
    { id: "Commuter", name: "Commuter" },
    { id: "Alphard", name: "Alphard" },
  ],
  Honda: [
    { id: "City", name: "City" },
    { id: "Civic", name: "Civic" },
    { id: "Accord", name: "Accord" },
    { id: "Jazz", name: "Jazz" },
    { id: "CR-V", name: "CR-V" },
    { id: "HR-V", name: "HR-V" },
    { id: "BR-V", name: "BR-V" },
    { id: "Freed", name: "Freed" },
  ],
  Isuzu: [
    { id: "D-Max", name: "D-Max" },
    { id: "MU-X", name: "MU-X" },
    { id: "Mu-7", name: "Mu-7" },
    { id: "V-Cross", name: "V-Cross" },
  ],
  Nissan: [
    { id: "Navara", name: "Navara" },
    { id: "Terra", name: "Terra" },
    { id: "Almera", name: "Almera" },
    { id: "Note", name: "Note" },
    { id: "X-Trail", name: "X-Trail" },
    { id: "Kicks", name: "Kicks" },
  ],
  Mazda: [
    { id: "BT-50", name: "BT-50" },
    { id: "CX-3", name: "CX-3" },
    { id: "CX-5", name: "CX-5" },
    { id: "CX-8", name: "CX-8" },
    { id: "Mazda2", name: "Mazda2" },
    { id: "Mazda3", name: "Mazda3" },
  ],
  Mitsubishi: [
    { id: "Triton", name: "Triton" },
    { id: "Pajero Sport", name: "Pajero Sport" },
    { id: "Attrage", name: "Attrage" },
    { id: "Mirage", name: "Mirage" },
    { id: "Outlander", name: "Outlander" },
    { id: "Xpander", name: "Xpander" },
  ],
  Ford: [
    { id: "Ranger", name: "Ranger" },
    { id: "Everest", name: "Everest" },
    { id: "Fiesta", name: "Fiesta" },
    { id: "Focus", name: "Focus" },
    { id: "EcoSport", name: "EcoSport" },
  ],
  Chevrolet: [
    { id: "Colorado", name: "Colorado" },
    { id: "Trailblazer", name: "Trailblazer" },
    { id: "Sonic", name: "Sonic" },
    { id: "Captiva", name: "Captiva" },
  ],
};

// ข้อมูลจังหวัดในประเทศไทย
export const provinces = [
  { id: "กรุงเทพมหานคร", name: "กรุงเทพมหานคร" },
  { id: "กระบี่", name: "กระบี่" },
  { id: "กาญจนบุรี", name: "กาญจนบุรี" },
  { id: "กาฬสินธุ์", name: "กาฬสินธุ์" },
  { id: "กำแพงเพชร", name: "กำแพงเพชร" },
  { id: "ขอนแก่น", name: "ขอนแก่น" },
  { id: "จันทบุรี", name: "จันทบุรี" },
  { id: "ฉะเชิงเทรา", name: "ฉะเชิงเทรา" },
  { id: "ชลบุรี", name: "ชลบุรี" },
  { id: "ชัยนาท", name: "ชัยนาท" },
  { id: "ชัยภูมิ", name: "ชัยภูมิ" },
  { id: "ชุมพร", name: "ชุมพร" },
  { id: "เชียงราย", name: "เชียงราย" },
  { id: "เชียงใหม่", name: "เชียงใหม่" },
  { id: "ตรัง", name: "ตรัง" },
  { id: "ตราด", name: "ตราด" },
  { id: "ตาก", name: "ตาก" },
  { id: "นครนายก", name: "นครนายก" },
  { id: "นครปฐม", name: "นครปฐม" },
  { id: "นครพนม", name: "นครพนม" },
  { id: "นครราชสีมา", name: "นครราชสีมา" },
  { id: "นครศรีธรรมราช", name: "นครศรีธรรมราช" },
  { id: "นครสวรรค์", name: "นครสวรรค์" },
  { id: "นนทบุรี", name: "นนทบุรี" },
  { id: "นราธิวาส", name: "นราธิวาส" },
  { id: "น่าน", name: "น่าน" },
  { id: "บึงกาฬ", name: "บึงกาฬ" },
  { id: "บุรีรัมย์", name: "บุรีรัมย์" },
  { id: "ปทุมธานี", name: "ปทุมธานี" },
  { id: "ประจวบคีรีขันธ์", name: "ประจวบคีรีขันธ์" },
  { id: "ปราจีนบุรี", name: "ปราจีนบุรี" },
  { id: "ปัตตานี", name: "ปัตตานี" },
  { id: "พระนครศรีอยุธยา", name: "พระนครศรีอยุธยา" },
  { id: "พังงา", name: "พังงา" },
  { id: "พัทลุง", name: "พัทลุง" },
  { id: "พิจิตร", name: "พิจิตร" },
  { id: "พิษณุโลก", name: "พิษณุโลก" },
  { id: "เพชรบุรี", name: "เพชรบุรี" },
  { id: "เพชรบูรณ์", name: "เพชรบูรณ์" },
  { id: "แพร่", name: "แพร่" },
  { id: "ภูเก็ต", name: "ภูเก็ต" },
  { id: "มหาสารคาม", name: "มหาสารคาม" },
  { id: "มุกดาหาร", name: "มุกดาหาร" },
  { id: "แม่ฮ่องสอน", name: "แม่ฮ่องสอน" },
  { id: "ยโสธร", name: "ยโสธร" },
  { id: "ยะลา", name: "ยะลา" },
  { id: "ร้อยเอ็ด", name: "ร้อยเอ็ด" },
  { id: "ระนอง", name: "ระนอง" },
  { id: "ระยอง", name: "ระยอง" },
  { id: "ราชบุรี", name: "ราชบุรี" },
  { id: "ลพบุรี", name: "ลพบุรี" },
  { id: "ลำปาง", name: "ลำปาง" },
  { id: "ลำพูน", name: "ลำพูน" },
  { id: "เลย", name: "เลย" },
  { id: "ศรีสะเกษ", name: "ศรีสะเกษ" },
  { id: "สกลนคร", name: "สกลนคร" },
  { id: "สงขลา", name: "สงขลา" },
  { id: "สตูล", name: "สตูล" },
  { id: "สมุทรปราการ", name: "สมุทรปราการ" },
  { id: "สมุทรสงคราม", name: "สมุทรสงคราม" },
  { id: "สมุทรสาคร", name: "สมุทรสาคร" },
  { id: "สระแก้ว", name: "สระแก้ว" },
  { id: "สระบุรี", name: "สระบุรี" },
  { id: "สิงห์บุรี", name: "สิงห์บุรี" },
  { id: "สุโขทัย", name: "สุโขทัย" },
  { id: "สุพรรณบุรี", name: "สุพรรณบุรี" },
  { id: "สุราษฎร์ธานี", name: "สุราษฎร์ธานี" },
  { id: "สุรินทร์", name: "สุรินทร์" },
  { id: "หนองคาย", name: "หนองคาย" },
  { id: "หนองบัวลำภู", name: "หนองบัวลำภู" },
  { id: "อ่างทอง", name: "อ่างทอง" },
  { id: "อำนาจเจริญ", name: "อำนาจเจริญ" },
  { id: "อุดรธานี", name: "อุดรธานี" },
  { id: "อุตรดิตถ์", name: "อุตรดิตถ์" },
  { id: "อุทัยธานี", name: "อุทัยธานี" },
  { id: "อุบลราชธานี", name: "อุบลราชธานี" },
];

// ฟังก์ชันสำหรับดึงรุ่นรถตามยี่ห้อ
export const getAvailableModels = (brand) => {
  return carModels[brand] || [];
};
